### ISSUE TITLE
Change the License for static linking

### ISSUE THREAD

**Issue by luisbg** [sdroege/rsplugin#7]
LGPL isn't the best for static linking. This is a proposal to switch to a more appropriate permissive license.

Which one do people recommend? I suggest MIT but IANAL. An other alternative is to explicitly add an exception about static linking, like GNU Guile does.
https://en.wikipedia.org/wiki/GPL_linking_exception

**Comment by sdroege** [comment]
MIT or BSD sounds ideal, most other Rust projects seem to do MIT / Apache but I'm not seeing the point in having Apache there as it only adds restrictions on top of MIT.

Guile is GPL with linking exception, no? That's basically LGPL then. Or can you link to a license text for clarification? Main problem with this approach is that it's a "new" license, not a well known one.

**Comment by luisbg** [comment]
I also prefer MIT.

No need to discuss the Guile license if we agree on MIT. I think that explicit exceptions aren't that good because it requires people reading the license text instead of automatically knowing by looking at the license name.

**Comment by sdroege** [comment]
Apache2 has stricter terms but includes a patent grant / retaliation clause, which is nice. So going with MIT and that makes sense, either you get just the code, or you get more restrictions but patent grant

Apache2 only makes no sense due to (L)GPL 2 incompatibilities (v3 is fine).

**Comment by sdroege** [comment]
Basically, AFAIU, it requires everybody contributing code, do also give you the right to use their patents involving that code. Which might not be nice for some people, but I think it makes sense. AFAIU it does not apply to any code you built upon unless you also distribute it under the terms of the Apache2 license, which you don't have to.

**Comment by luisbg** [comment]
It does make sense.

But I am wondering if companies would be scared of Apache2, because of the risk of patent leaks.

**Comment by sdroege** [comment]
Android is Apache2, so companies apparently don't worry. It's also not requiring that modifications to the existing code are to be released under the same license, only that the original code must be.

**Comment by luisbg** [comment]
I'm fine with the Apache2/MIT solution. It removes all fears.

Unfortunately it means changes on-top of the shared code don't have to be contributed back, but that is a worthy sacrifice.

**Comment by sdroege** [comment]
Great, so we only need @suhr to agree for completeness (see https://github.com/sdroege/rsplugin/pull/6)

**Comment by suhr** [comment]
Sure, you can change it.

**Comment by luisbg** [comment]
@sdroege if you want I can send you a pull request that changes the COPYING file to be the Apache2 license, plus the header of all the .rs/.c files.
